title: GitHub Pages
author: banaanihillo
email: banaanihillo@protonmail.ch
theme: jekyll-theme-midnight
description: > # this means to ignore newlines until "baseurl:"
  GitHub Pages

# social links
github_username:  banaanihillo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
